#!/usr/bin/env python3
"""Generate the `/.well-known/skills/` publishing artifacts for Hermes Agent.

Hermes' hub can install skills from any domain that exposes
`/.well-known/skills/index.json` (`WellKnownSkillSource` in hermes-agent). That
route is how *all 39* skills become installable by name — the `hermes skills
tap` route can't, because a tap is one repo plus one base path and `tap add`
refuses a second entry per repo, so it only ever reaches the 35 under `skills/`.

Hermes derives every fetch URL from the index URL — `{index_url_dir}/{name}/
SKILL.md` — and an index entry cannot name a different host (`files` entries are
validated as relative paths). But `_guarded_http_get` **follows redirects**, up
to 5 hops, re-validating each. So the website publishes no skill content at all:
it redirects `/.well-known/skills/*` to raw.githubusercontent.com, and the
skills stay single-source in this repo. That is what "point index.json at
GitHub" means here.

Two artifacts, both committed and both regenerated by this script:

- `.well-known/skills/index.json` — the index Hermes reads. Served from the
  website via a redirect to this file's raw URL, so it ships with the skills it
  describes rather than drifting in a second repo.
- `.well-known/skills/cloudflare-redirects.txt` — the `_redirects` block the
  website needs. One line per skill, because a skill's *name* (frontmatter,
  e.g. `chronicle-status`) is not its *directory* (`status`), so no single
  wildcard can express the mapping. Paste it into chronicle-web's
  `home/public/_redirects` between the generated markers.

Run `--check` in CI to fail when either artifact is stale.

    python3 scripts/gen_wellknown_index.py           # write
    python3 scripts/gen_wellknown_index.py --check   # verify, write nothing
"""

from __future__ import annotations

import argparse
import json
import pathlib
import re
import sys
from typing import Dict, List

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

# Where the skills live, and the raw.githubusercontent path each maps to.
SKILL_ROOTS = ("skills", "research-plugin/skills")

RAW_BASE = "https://raw.githubusercontent.com/methodic-research/skills/main"
SITE_PATH = "/.well-known/skills"

OUT_DIR = REPO_ROOT / ".well-known" / "skills"
INDEX_PATH = OUT_DIR / "index.json"
REDIRECTS_PATH = OUT_DIR / "cloudflare-redirects.txt"

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)

REDIRECTS_HEADER = """\
# BEGIN generated: methodic-research/skills well-known skills
# Generated by scripts/gen_wellknown_index.py in methodic-research/skills.
# Do not hand-edit — re-run that script and paste the block back.
#
# Hermes Agent installs from /.well-known/skills/index.json and then fetches
# {index_dir}/{skill-name}/SKILL.md. Its fetcher follows redirects (5 hops max,
# each re-validated), so these 302s let the site publish the skills without
# hosting a copy of any of them. One line per skill: a skill's name is its
# frontmatter `name`, which is not its directory, so a wildcard can't map them.
"""

REDIRECTS_FOOTER = "# END generated: methodic-research/skills well-known skills\n"


def parse_frontmatter(text: str) -> Dict[str, str]:
    """Pull `name` and `description` out of a SKILL.md's YAML frontmatter.

    Deliberately not a YAML parse: the only shapes in this repo are a plain
    scalar and a `|`-style block, and keeping it dependency-free means CI can
    run this in the cheap secret-less lint job.
    """
    match = FRONTMATTER.match(text)
    if not match:
        return {}
    block = match.group(1)
    fields: Dict[str, str] = {}

    scalar = re.search(r"^name:[ \t]*(.+?)[ \t]*$", block, re.M)
    if scalar:
        fields["name"] = scalar.group(1).strip().strip("'\"")

    # description is usually a `|` block; fall back to an inline scalar.
    blk = re.search(r"^description:[ \t]*\|[-+]?[ \t]*\n((?:[ \t]+.*\n?)+)", block, re.M)
    if blk:
        lines = [ln.strip() for ln in blk.group(1).splitlines()]
        fields["description"] = " ".join(ln for ln in lines if ln)
    else:
        inline = re.search(r"^description:[ \t]*(.+?)[ \t]*$", block, re.M)
        if inline:
            fields["description"] = inline.group(1).strip().strip("'\"")

    return fields


def collect() -> List[Dict[str, str]]:
    """Every skill, as {name, description, repo_path}, sorted by name."""
    skills: List[Dict[str, str]] = []
    seen: Dict[str, str] = {}

    for root_rel in SKILL_ROOTS:
        root = REPO_ROOT / root_rel
        if not root.is_dir():
            sys.exit(f"error: missing skill root {root_rel}")
        for skill_md in sorted(root.glob("*/SKILL.md")):
            fields = parse_frontmatter(skill_md.read_text(encoding="utf-8"))
            name = fields.get("name") or skill_md.parent.name
            if name in seen:
                sys.exit(
                    f"error: duplicate skill name {name!r} in {seen[name]} and "
                    f"{skill_md.parent.relative_to(REPO_ROOT)} — names are the "
                    "install identifier and must be unique"
                )
            seen[name] = str(skill_md.parent.relative_to(REPO_ROOT))
            skills.append({
                "name": name,
                "description": fields.get("description", ""),
                "repo_path": f"{root_rel}/{skill_md.parent.name}",
            })

    skills.sort(key=lambda s: s["name"])
    return skills


def render_index(skills: List[Dict[str, str]]) -> str:
    """Exactly the shape Hermes reads: {"skills": [{name, description, files}]}.

    Nothing else — unknown top-level keys are ignored by Hermes, but other
    agentskills.io consumers read this file too, so it stays to the contract.
    """
    payload = {
        "skills": [
            {
                "name": s["name"],
                "description": s["description"],
                "files": ["SKILL.md"],
            }
            for s in skills
        ]
    }
    return json.dumps(payload, indent=2, ensure_ascii=False) + "\n"


def render_redirects(skills: List[Dict[str, str]]) -> str:
    index_src = f"{SITE_PATH}/index.json"
    index_dst = f"{RAW_BASE}/.well-known/skills/index.json"

    rows = [(index_src, index_dst)]
    rows += [
        (f"{SITE_PATH}/{s['name']}/SKILL.md", f"{RAW_BASE}/{s['repo_path']}/SKILL.md")
        for s in skills
    ]
    width = max(len(src) for src, _ in rows)
    body = "\n".join(f"{src.ljust(width)}  {dst}  302" for src, dst in rows)
    return REDIRECTS_HEADER + body + "\n" + REDIRECTS_FOOTER


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate the /.well-known/skills publishing artifacts.",
    )
    parser.add_argument("--check", action="store_true",
                        help="fail if the committed artifacts are stale; write nothing")
    args = parser.parse_args()

    skills = collect()
    artifacts = {INDEX_PATH: render_index(skills), REDIRECTS_PATH: render_redirects(skills)}

    if args.check:
        stale = [
            path for path, want in artifacts.items()
            if not path.exists() or path.read_text(encoding="utf-8") != want
        ]
        if stale:
            for path in stale:
                print(f"stale: {path.relative_to(REPO_ROOT)}")
            print("\nRun `python3 scripts/gen_wellknown_index.py` and commit the result.")
            return 1
        print(f"well-known artifacts current — {len(skills)} skills indexed.")
        return 0

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    for path, text in artifacts.items():
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path.relative_to(REPO_ROOT)}")
    print(f"{len(skills)} skills indexed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
